version: '3.7'

services:
  streamlitapp:
    build:
      context: ./streamlit
    image: mynsun/streamlitapp:latest
    container_name: streamlitapp
    ports:
      - "8501:8501"
    env_file:
      - ./.env
    networks:
      - app-network
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}

    restart: always

  fastapi-service:
    build:
      context: ./fastapi_service
    image: mynsun/fastapi-backend:latest
    container_name: fastapi-backend
    ports:
      - "3000:3000"
    networks:
      - app-network
    depends_on:
      - fastapi
    env_file:
      - ./.env

    restart: always

networks:
  app-network:
    driver: bridge