name: Docker Build, Push & Deploy

on:
  push:
    branches: [ "main" ]

env:
  DOCKER_HUB_USERNAME: ${{ secrets.DOCKER_USERNAME }}
  DOCKER_HUB_TOKEN: ${{ secrets.DOCKER_PASSWORD }}
  STREAMLIT_IMAGE_NAME: mynsun/streamlitapp
  FASTAPI_IMAGE_NAME: mynsun/fastapi-backend
  EC2_HOST: ${{ secrets.HOST }}
  EC2_USERNAME: ${{ secrets.USERNAME }}
  EC2_KEY: ${{ secrets.KEY }}
  EC2_PORT: ${{ secrets.PORT }}
  OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}

jobs:
  build-push-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ env.DOCKER_HUB_USERNAME }}
          password: ${{ env.DOCKER_HUB_TOKEN }}

      - name: Build and Push Streamlit Docker Image
        uses: docker/build-push-action@v5
        with:
          context: ./streamlit
          dockerfile: Dockerfile
          push: true
          tags: ${{ env.STREAMLIT_IMAGE_NAME }}:latest
          no-cache: true
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Build and Push FastAPI Docker Image
        uses: docker/build-push-action@v5
        with:
          context: ./fastapi_service
          dockerfile: Dockerfile
          push: true
          tags: ${{ env.FASTAPI_IMAGE_NAME }}:latest
          no-cache: true
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Deploy to EC2 (SSH)
        uses: appleboy/ssh-action@master
        with:
          host: ${{ env.EC2_HOST }}
          username: ${{ env.EC2_USERNAME }}
          key: ${{ env.EC2_KEY }}
          port: ${{ env.EC2_PORT }}
          envs: OPENAI_API_KEY
          script: |
            PROJECT_DIR="/home/${{ env.EC2_USERNAME }}/project"

            if [ ! -d "$PROJECT_DIR" ]; then
              exit 1
            fi
            cd "$PROJECT_DIR" || { exit 1; }

            if ! systemctl is-active --quiet docker; then
              sudo systemctl start docker || { exit 1; }
              sleep 5
            fi

            if ! id -nG "$USER" | grep -qw "docker"; then
              sudo usermod -aG docker "$USER" || { exit 1; }
            fi

            docker-compose pull || { exit 1; }

            docker-compose down || true
            
            docker-compose up -d --force-recreate || { exit 1; }

            docker ps -a

            docker logs nutrition_streamlit_app --tail 50 || true
            docker logs nutrition_fastapi_backend --tail 50 || true

            docker system prune -f || true
